In [32]:
# A hello world program for classifying apples and oranges
# This is based off youtube video https://www.youtube.com/watch?v=cKxRvEZd3Mw
import sklearn
from sklearn import tree

In [33]:
# in the second column, 1=smooth, and 0=bumpy
features=[[140,1],[130,1],[150,0],[170,0]]

In [34]:
# in the labels column, 0=apple, and 1=orange
labels=[0,0,1,1]

In [35]:
# create empty classifier
clf=tree.DecisionTreeClassifier()

In [36]:
# now use fit function to find patterns in data and train the clasifier
clf.fit(features,labels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [48]:
# now let's test the classifier on a new example
# look at your original training set - this should certainly be an orange!
print(clf.predict([145,0]))

[0]


/Users/leonardorinaldi/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [ ]:
# Visualizing a decision tree
# Based on video https://www.youtube.com/watch?v=tNa99PG8hR8
# Will use a dataset that has four features to describe three different types of irises
# There are 150 examples total
# Scikit already makes it easy to import iris dataset

In [64]:
# set the dataset equal to variable iris
from sklearn import datasets
iris=datasets.load_iris()

In [66]:
# let's do a few things to get comfortable working with the dataset before we do the classifier
# you can see feature details
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [67]:
# or you can see names of the flowers (labels) using "target_names"
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [68]:
# since its an array, you can see specific examples (rows in the array using "data")
print(iris.data[0])

[ 5.1  3.5  1.4  0.2]


In [69]:
# likewise using "target" gets you the labels for a particular row
# 0 means it's a setosa
print (iris.target[0])

0


In [71]:
# you can see the whole dataset this way
for i in range(len(iris.target)):
    print ("Example %d: label %s, features %s" % (i,iris.target[i],iris.data[i]))

Example 0: label 0, features [ 5.1  3.5  1.4  0.2]
Example 1: label 0, features [ 4.9  3.   1.4  0.2]
Example 2: label 0, features [ 4.7  3.2  1.3  0.2]
Example 3: label 0, features [ 4.6  3.1  1.5  0.2]
Example 4: label 0, features [ 5.   3.6  1.4  0.2]
Example 5: label 0, features [ 5.4  3.9  1.7  0.4]
Example 6: label 0, features [ 4.6  3.4  1.4  0.3]
Example 7: label 0, features [ 5.   3.4  1.5  0.2]
Example 8: label 0, features [ 4.4  2.9  1.4  0.2]
Example 9: label 0, features [ 4.9  3.1  1.5  0.1]
Example 10: label 0, features [ 5.4  3.7  1.5  0.2]
Example 11: label 0, features [ 4.8  3.4  1.6  0.2]
Example 12: label 0, features [ 4.8  3.   1.4  0.1]
Example 13: label 0, features [ 4.3  3.   1.1  0.1]
Example 14: label 0, features [ 5.8  4.   1.2  0.2]
Example 15: label 0, features [ 5.7  4.4  1.5  0.4]
Example 16: label 0, features [ 5.4  3.9  1.3  0.4]
Example 17: label 0, features [ 5.1  3.5  1.4  0.3]
Example 18: label 0, features [ 5.7  3.8  1.7  0.3]
Example 19: label 0, f

In [72]:
# now let's work on the classifier
# we will need to set aside some example data to test the classifier's accuracy later
# for this simple example, we'll remove just three rows - these happen to contain one of each type of iris
# let's start at the beginning again, and add numpy functionality as well
import numpy as np
from sklearn import datasets
from sklearn import tree
iris=datasets.load_iris()
# define the data rows you'll set aside for testing later
test_idx=[0,50,100]

In [73]:
# define training data as iris datset with testing rows deleted
train_target=np.delete(iris.target, test_idx)
train_data=np.delete(iris.data, test_idx, axis=0)

In [74]:
# define testing data as just the rows in iris that you defined earlier
test_target=iris.target[test_idx]
test_data=iris.data[test_idx]

In [75]:
# now let's define a decision tree classifier and train it on our data like orange and apple example
clf=tree.DecisionTreeClassifier()
clf=clf.fit(train_data,train_target)

In [77]:
# now let's test the clssifier
# look at the test target data
print(test_target)
# compare that to the classifier's predicted results
print(clf.predict(test_data))
# if they match you are looking good

[0 1 2]
[0 1 2]


In [80]:
# new video https://www.youtube.com/watch?v=84gqSbLcBFE
# we're going to use iris again
import numpy as np
from sklearn import datasets
iris=datasets.load_iris()

In [81]:
# this time we'll define data/features as x and labels/target as y
# since the pattern is kind of like f(X)=y
X=iris.data
y=iris.target

In [82]:
# there is a handy function that makes it easier to partition training and test data
# using .5 means half the data will be used for testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

In [84]:
# let's do decision tree again using the training data
from sklearn import tree
my_classifier=tree.DecisionTreeClassifier()
my_classifier.fit(X_train,y_train)
predictions=my_classifier.predict(X_test)

In [85]:
# compare predictions to the test labels
print(y_test)
print(predictions)

[1 0 2 2 0 1 0 0 0 1 1 1 1 1 2 1 0 1 2 1 0 2 2 2 1 0 1 1 2 2 2 0 2 0 1 0 0
 1 2 2 1 0 0 2 1 0 0 2 1 0 0 2 0 2 1 1 0 2 0 2 1 2 2 2 2 2 0 0 2 0 0 0 1 1
 1]
[1 0 2 2 0 1 0 0 0 1 1 1 1 1 2 1 0 1 2 1 0 2 2 2 1 0 1 1 2 2 2 0 2 0 2 0 0
 1 2 2 1 0 0 2 1 0 0 2 1 0 0 2 0 1 1 1 0 2 0 2 1 2 2 2 2 2 0 0 1 0 0 0 1 1
 1]


In [87]:
# too many to compare - how do we see how accurate it is?
# use this accuracy function and put into it what you are comparing
from sklearn.metrics import accuracy_score
print (accuracy_score(y_test,predictions))

0.96


In [89]:
# we can use an alternative approach instead of a decision tree
# This is K Nearest neighbors
# notice that while this is a different classifier, a lot of the syntax...
# is the same, such as .fit and .predict
from sklearn.neighbors import KNeighborsClassifier
my_classifier=KNeighborsClassifier()
my_classifier.fit(X_train, y_train)
predictions=my_classifier.predict(X_test)
print (accuracy_score(y_test, predictions))

0.986666666667


In [6]:
# Machine Learning recipes #5
# Write your own classifier - a simple version of K nearest neighbors
# Going to take our previous KNeighborsClassifier code but this time...
# ...We'll write it ourselves

# random is just temporarily used initially to populate the predictions before we write the real classifier code
import random

# So bringing back the code, but adding a class to it which we can call whatever we want
class ScrappyKNN():
# defining the fit method for the class - will require parameters from the training set as inputs
    def fit(self, X_train, y_train):
        self.X_train=X_train
        self.y_train=y_train
        pass

# and defining the predict method which will predict Y from the X test data
    def predict(self,X_test):
        # needs to return a list of predictions
        predictions=[]
        for row in X_test:
            label=random.choice(self.y_train)
            predictions.append(label)
        return predictions
    
import numpy as np
from sklearn import datasets
iris=datasets.load_iris()
X=iris.data
y=iris.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

# now we'll change our pipeline to use our new class instead of the imported KNeighborsClassifier from before
my_classifier=ScrappyKNN()
my_classifier.fit(X_train, y_train)
predictions=my_classifier.predict(X_test)

from sklearn.metrics import accuracy_score
print (accuracy_score(y_test, predictions))

# the answer here will be close to 0.33 - since we have three types of iris' and populated the label randomly

0.36


In [12]:
# now we're going to build out a K nearest neighbor classifier
# all this does is find a certain # of neighbors near a point
# whatever the majority of them are, that's what we predict the point to be
# this uses something like the euclidean pythagoreum theorum (a^2+b^2=c^2) to find the distance
# we can use a function that anaconda has available to us to help measure the distance
from scipy.spatial import distance

# here a may become a point from our training data, and b a point from testing data
def euc(a,b):
    return distance.euclidean(a,b)

class ScrappyKNN():
    def fit(self, X_train, y_train):
        self.X_train=X_train
        self.y_train=y_train
        pass

    def predict(self,X_test):
        # needs to return a list of predictions, so make this an array
        predictions=[]
        for row in X_test:
            # this time we replace random label with label of closest point to the test point
            # will create this "closest" function in a second
            label=self.closest(row)
            predictions.append(label)
        return predictions
    
    def closest(self,row):
        # this variable keep track of the closest one we found so far
        # remember "row" is each row in x test - so we're measuring distance of that to points in training data
        # this is measuring distance in multi-dimensional space using all the dimensions of the two rows
        # initiate by comparing the test to first row (row 0) of the training data and setting that as best distance
        best_dist=euc(row,self.X_train[0])
        best_index=0
        # iterate over all the other points, and everytime we find a closer one, update best distance and row index
        for i in range(1,len(self.X_train)):
            dist=euc(row,self.X_train[i])
            if dist<best_dist:
                best_dist=dist
                best_index=i
        return self.y_train[best_index]
    
import numpy as np
from sklearn import datasets
iris=datasets.load_iris()
X=iris.data
y=iris.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

my_classifier=ScrappyKNN()
my_classifier.fit(X_train, y_train)
predictions=my_classifier.predict(X_test)

from sklearn.metrics import accuracy_score
print (accuracy_score(y_test, predictions))

0.96


In [ ]:
# episode 6 - building our own image classifier using TensorFlow for Poets
# This classifier uses deep learning to classify images with labels
# Here x is a 2D image (e.g., png or jpg file), and y is a label like "rose"
# Why is deep learning so great? Because it will extract the features itself from the image pixels
# We don't need to create our own features such as "bumpy texture", etc., etc.
# TF Learn is an easy to use library that sits on top of TensorFlow - similar to sklearn that we used earlier
# In this case, TF for Poets leverages Inception - a huge image classification model with millions of parameters...
# ...That can differentiate a large number of impage types
# When you add your data it only trains the final layer of that network, so training takes "reasonable" time
# According to Josh, the script will take about 20 minutes to train the classifier
# GO TO TENSORFLOW FOR POETS WEBSITE AND FOLLOW INSTRUCTIONS